#Global configuration
spring:
    application.name: MongoDemo
    aop.proxy-target-class: true
#Tomcat configuration
server.port: 9000

#Log level configuration
logging:
    level:
        root: ERROR
        mongo.MongoDemo: INFO
        org:
            springframework:
                data.mongodb: INFO
                boot.web.embedded.tomcat: INFO

#Db configuration
spring.data.mongodb.uri: mongodb://localhost:27017/mongo
